/** Reference data: categories, neighbourhoods and the demo catalogue. */

export const CATEGORIES = [
  ['gym', 'Gym & Fitness', 'dumbbell'],
  ['yoga', 'Yoga & Wellness', 'lotus'],
  ['meals', 'Tiffin & Meals', 'utensils'],
  ['laundry', 'Laundry & Ironing', 'shirt'],
  ['car-care', 'Car & Bike Care', 'car'],
  ['tuition', 'Tuition & Coaching', 'book'],
  ['salon', 'Salon & Grooming', 'scissors'],
  ['dance', 'Dance & Zumba', 'music'],
  ['music', 'Music Classes', 'guitar'],
  ['swimming', 'Swimming', 'waves'],
  ['coworking', 'Coworking & Study', 'desk'],
  ['dairy', 'Milk & Daily Essentials', 'milk'],
  ['home-cleaning', 'Home Cleaning', 'sparkle'],
  ['sports', 'Sports Coaching', 'trophy'],
  ['pet-care', 'Pet Care', 'paw'],
];

export const LOCATIONS = [
  ['Rajpur Road', 'Dehradun', 30.3440, 78.0610],
  ['Clement Town', 'Dehradun', 30.2690, 78.0090],
  ['Prem Nagar', 'Dehradun', 30.3350, 77.9570],
  ['Ballupur', 'Dehradun', 30.3350, 78.0120],
  ['ISBT', 'Dehradun', 30.2880, 77.9990],
  ['Sahastradhara Road', 'Dehradun', 30.3470, 78.0830],
  ['Jakhan', 'Dehradun', 30.3650, 78.0680],
  ['Patel Nagar', 'Dehradun', 30.3050, 78.0200],
  ['Dalanwala', 'Dehradun', 30.3170, 78.0550],
  ['Race Course', 'Dehradun', 30.3090, 78.0470],
  ['Vasant Vihar', 'Dehradun', 30.3320, 78.0050],
  ['Kaulagarh', 'Dehradun', 30.3530, 78.0150],
  ['Clock Tower', 'Dehradun', 30.3240, 78.0410],
  ['Nehru Colony', 'Dehradun', 30.3000, 78.0600],
  ['Selaqui', 'Dehradun', 30.3700, 77.8650],
  ['Tapovan', 'Rishikesh', 30.1290, 78.3200],
];

const ALL = 'mon,tue,wed,thu,fri,sat,sun';
const WEEK6 = 'mon,tue,wed,thu,fri,sat';
const WEEKDAYS = 'mon,tue,wed,thu,fri';

/**
 * [name, category, short, description, price ₹, days, hours, usage allowed (null = unlimited),
 *  unit, restrictions, rules, type, plans, areas]
 */
export const DEMO_SERVICES = [
  ['Iron Paradise Gym', 'gym', 'Full-access strength and cardio floor with a trainer on every shift.',
    'Free weights, a squat rack zone, 30+ cardio machines and a trainer on the floor every shift. Your first week includes a posture and goals assessment. Lockers and showers included.',
    999, WEEK6, '5:30 am – 10:30 pm', null, 'visits', 'One visit per day. Guests not included.', 'Carry a towel and indoor shoes. Show your Subtize.ai card at reception.', 'in_person', '1,3,6', ['Rajpur Road', 'Ballupur', 'Race Course', 'Clement Town']],
  ['Pulse CrossFit Box', 'gym', 'Coached CrossFit classes, capped at 14 people.',
    'Every session is coached: a warm-up, a skill block and a WOD scaled to your level. Beginners get two foundation classes in the first week.',
    1799, WEEK6, 'Batches at 6, 7, 8 am and 6, 7 pm', 20, 'classes', 'Book your batch a day ahead. Missed bookings count as used.', 'No outdoor shoes on the rig floor.', 'in_person', '1,3', ['Jakhan', 'Vasant Vihar']],
  ['Budget Fit Studio', 'gym', 'No-frills gym with the basics done well, open all week.',
    'Machines, dumbbells to 40 kg and a small cardio corner. Good for students and early risers who just want to train.',
    649, ALL, '5 am – 11 pm', null, 'visits', 'Off-peak only on weekends (before 4 pm).', 'Re-rack your weights.', 'in_person', '1,3', ['Prem Nagar', 'Selaqui', 'ISBT', 'Patel Nagar']],
  ['Home Personal Training', 'gym', 'A certified trainer comes to you three times a week.',
    'Forty-five minute sessions at your home or society gym. Equipment brought along: bands, kettlebells and a mat. Plans reviewed every fortnight.',
    4499, WEEKDAYS, 'Slots 6 am – 9 pm', 12, 'sessions', 'Reschedule at least 4 hours ahead.', 'A clear 2 × 2 m space is needed.', 'doorstep', '1', ['Dalanwala', 'Rajpur Road']],

  ['Sunrise Hatha Yoga', 'yoga', 'Morning hatha yoga and pranayam in a calm garden studio.',
    'Traditional hatha sequences with breathwork and a short meditation to close. Suited to all levels, including anyone returning after an injury.',
    799, WEEK6, '6:00 – 7:15 am', null, 'sessions', 'One session per day.', 'Arrive 10 minutes early. Mats provided.', 'in_person', '1,3,6', ['Tapovan', 'Rajpur Road', 'Vasant Vihar', 'Dalanwala']],
  ['Power Vinyasa Flow', 'yoga', 'Faster evening flow classes for strength and flexibility.',
    'Sixty-minute vinyasa classes that build heat. Expect planks, balances and a long stretch at the end.',
    1199, 'mon,wed,fri,sat', '6:30 – 7:30 pm', 16, 'classes', 'Four classes a week at most.', 'Bring your own mat if you can.', 'in_person', '1,3', ['Jakhan', 'Dalanwala']],
  ['Online Meditation Circle', 'yoga', 'Live guided meditation on video, every morning.',
    'Twenty-five minutes of guided breathing and meditation over video, plus a weekly Q&A with the teacher.',
    349, ALL, '7:00 – 7:25 am', null, 'sessions', 'Camera optional.', 'Join a minute early; the room locks at start.', 'online', '1,3,6,12', ['Clock Tower']],

  ['Maa Ki Rasoi Tiffin', 'meals', 'Home-style veg lunch and dinner delivered hot.',
    'Two rotis, rice, dal, sabzi and salad; a sweet on Sundays. Delivered in steel tiffins that we collect the next day.',
    2999, ALL, 'Lunch 12:30 pm, dinner 8 pm', 60, 'meals', 'Skip a meal by 10 am (lunch) or 5 pm (dinner) to carry it forward.', 'Return tiffins washed.', 'doorstep', '1,3', ['Prem Nagar', 'Ballupur', 'Clement Town', 'Patel Nagar', 'ISBT']],
  ['Protein Box Meal Plan', 'meals', 'High-protein lunch bowls counted for macros.',
    'Chicken, paneer or tofu bowls with measured macros on every label. Weekly menu posted on Saturday.',
    3999, WEEKDAYS, 'Delivered 12 – 1 pm', 22, 'meals', 'Veg and non-veg cannot be mixed in one plan.', 'Choose your base protein when you subscribe.', 'doorstep', '1', ['Rajpur Road', 'Race Course']],
  ['Student Mess Pass', 'meals', 'Unlimited-thali dine-in mess near the colleges.',
    'Breakfast, lunch and dinner at the mess counter. Unlimited rotis and rice; sabzi changes daily.',
    2499, ALL, '8 am – 10 pm', 90, 'meals', 'Dine-in only. Three meals a day at most.', 'Show your card at the counter.', 'in_person', '1,3', ['Prem Nagar', 'Selaqui', 'Clement Town']],

  ['FreshFold Laundry', 'laundry', 'Wash, dry and fold with doorstep pickup twice a week.',
    'Pickup on Monday and Thursday, back within 48 hours, folded and bagged. Up to 8 kg per pickup.',
    899, 'mon,thu', 'Pickups 8 – 11 am', 8, 'pickups', 'Up to 8 kg per pickup. Woollens and delicates cost extra.', 'Empty your pockets.', 'doorstep', '1,3', ['Vasant Vihar', 'Ballupur', 'Kaulagarh', 'Prem Nagar']],
  ['Crisp Press Ironing', 'laundry', 'Steam ironing for up to 60 garments a month.',
    'Drop off or schedule a pickup. Shirts come back on hangers, everything else folded.',
    499, WEEK6, '9 am – 8 pm', 60, 'garments', 'Silk and sarees count as two.', 'Pickups need a day of notice.', 'doorstep', '1,3,6', ['Patel Nagar', 'Nehru Colony', 'Dalanwala']],

  ['ShineOn Car Wash', 'car-care', 'Doorstep exterior wash four times a month.',
    'A waterless exterior wash at your parking spot, with tyre shine and a quick interior vacuum on every second visit.',
    799, WEEK6, 'Early morning, 6 – 9 am', 4, 'washes', 'One vehicle per plan. SUVs have their own plan.', 'Leave the car unlocked or hand over keys.', 'doorstep', '1,3', ['Rajpur Road', 'Jakhan', 'Sahastradhara Road', 'Dalanwala']],
  ['Daily Car Cleaning', 'car-care', 'Daily exterior wipe-down and weekly interior clean.',
    'A cleaner wipes your car every morning, with a full interior vacuum on Sundays.',
    599, ALL, '6 – 8 am', 30, 'cleans', 'Hatchback and sedan only.', 'Report a missed clean within 24 hours.', 'doorstep', '1,3,6', ['Vasant Vihar', 'Kaulagarh', 'Patel Nagar']],
  ['Bike Care Club', 'car-care', 'Monthly bike wash plus a chain clean and lube.',
    'Two washes and one chain service per month at the workshop, plus priority slots for repairs.',
    349, WEEK6, '10 am – 7 pm', 3, 'services', 'Parts and repairs are billed separately.', 'Book ahead on weekends.', 'in_person', '1,3,6', ['ISBT', 'Prem Nagar', 'Clement Town']],

  ['Bright Minds Maths Tuition', 'tuition', 'Small-batch maths for classes 8 to 10, CBSE and ICSE.',
    'Batches of 8. Weekly tests, doubt sessions on Saturday and a monthly progress note to parents.',
    1499, 'mon,wed,fri,sat', '4 – 6 pm', 13, 'classes', 'Batch is fixed once assigned.', 'Bring the previous test for the doubt class.', 'in_person', '1,3,6', ['Dalanwala', 'Race Course', 'Ballupur']],
  ['JEE Foundation Coaching', 'tuition', 'Physics, chemistry and maths foundation for classes 9–11.',
    'Three subjects, concept-first teaching and fortnightly tests with ranks.',
    3499, WEEK6, '5 – 8 pm', 24, 'classes', 'Attendance below 75% pauses test ranking.', 'Phones stay in bags.', 'in_person', '1,3,6,12', ['Clock Tower', 'Patel Nagar']],
  ['Spoken English Online', 'tuition', 'Live spoken English practice in groups of six.',
    'Conversation-led sessions on video with a trainer. Pronunciation, interview practice and presentation feedback.',
    899, 'tue,thu,sat', '7 – 8 pm', 12, 'sessions', 'Camera on for speaking rounds.', 'Join from a quiet room.', 'online', '1,3', ['Clock Tower']],

  ['The Grooming Lounge', 'salon', 'Two haircuts and a beard trim every month.',
    'Men\'s grooming membership: two haircuts, two beard trims and one head massage a month. Walk in or book.',
    699, 'tue,wed,thu,fri,sat,sun', '10 am – 9 pm', 5, 'services', 'Colour and treatments are extra.', 'Book weekend slots a day ahead.', 'in_person', '1,3,6', ['Rajpur Road', 'Patel Nagar', 'Prem Nagar', 'Ballupur', 'Clement Town']],
  ['Glow Beauty Studio', 'salon', 'Monthly facial, threading and a hair spa.',
    'One clean-up facial, unlimited threading and one hair spa each month.',
    1299, 'tue,wed,thu,fri,sat,sun', '11 am – 8 pm', 6, 'services', 'Waxing is billed separately.', 'Cancel at least 3 hours before a booking.', 'in_person', '1,3', ['Dalanwala', 'Jakhan', 'Vasant Vihar']],

  ['Rhythm Zumba Studio', 'dance', 'High-energy Zumba, five evenings a week.',
    'Forty-five minute Zumba and dance-fitness classes. No dance background needed.',
    899, 'mon,tue,wed,thu,fri', '6 – 6:45 pm and 7 – 7:45 pm', 20, 'classes', 'Book your batch in the app.', 'Indoor shoes only.', 'in_person', '1,3', ['Race Course', 'Ballupur', 'Kaulagarh', 'Clock Tower']],
  ['Kathak & Bollywood Academy', 'dance', 'Kathak basics and Bollywood choreography for all ages.',
    'Weekend Kathak for kids and adults, plus a Bollywood batch on Wednesday evenings. Annual showcase in March.',
    1100, 'wed,sat,sun', 'Wed 6 pm, weekends 10 am', 12, 'classes', 'Kids batch is ages 7–14.', 'Ghungroos are not provided.', 'in_person', '1,3,6', ['Dalanwala', 'Clement Town']],

  ['Strings Guitar School', 'music', 'Weekly guitar lessons, acoustic or electric.',
    'One-to-one or pairs, following a graded syllabus. Instruments available to borrow during class.',
    1499, 'tue,thu,sat', '3 – 8 pm', 8, 'lessons', 'Lessons are 45 minutes.', 'Reschedule up to 12 hours ahead.', 'in_person', '1,3,6', ['Rajpur Road', 'Vasant Vihar']],
  ['Swar Vocal & Keyboard', 'music', 'Hindustani vocal and keyboard classes.',
    'Two classes a week in either vocal or keyboard. Monthly baithak for students.',
    1299, 'mon,wed,fri', '4 – 8 pm', 8, 'lessons', 'Pick one instrument per plan.', 'Practise at home between classes.', 'in_person', '1,3', ['Clock Tower', 'Nehru Colony']],

  ['AquaLife Swim Club', 'swimming', 'Heated pool access with lane swim and coaching slots.',
    'Heated 25 m pool. Lane swim any open slot, plus two coached sessions a week for beginners.',
    1599, 'tue,wed,thu,fri,sat,sun', '6 – 10 am and 4 – 8 pm', 20, 'swims', 'Swim caps are required.', 'Shower before entering the pool.', 'in_person', '1,3', ['Sahastradhara Road', 'Rajpur Road']],

  ['Focus Desk Coworking', 'coworking', 'Hot desk with Wi-Fi, coffee and a meeting room hour.',
    'Unlimited hot-desk use on weekdays, fast Wi-Fi, filter coffee and 4 hours of meeting room time a month.',
    2499, WEEKDAYS, '9 am – 9 pm', null, 'days', 'Meeting room hours do not roll over.', 'Keep calls to the phone booths.', 'in_person', '1,3,6', ['Rajpur Road', 'Race Course', 'Clock Tower']],
  ['Silent Library Reading Room', 'coworking', 'AC reading room for exam prep, open late.',
    'Reserved seat, locker, drinking water and power at every desk. Strict silence.',
    899, ALL, '6 am – midnight', null, 'days', 'Seat is assigned for the month.', 'Phones on silent.', 'in_person', '1,3,6', ['Prem Nagar', 'Ballupur', 'Selaqui', 'Clement Town', 'Clock Tower']],

  ['Doon Dairy Fresh Milk', 'dairy', 'A litre of fresh cow milk at your door every morning.',
    'Unpackaged milk from partner farms, delivered by 7 am in returnable glass bottles.',
    1950, ALL, 'Delivered by 7 am', 30, 'litres', 'Pause deliveries by 8 pm the day before.', 'Leave the empty bottle out.', 'doorstep', '1,3', ['Vasant Vihar', 'Jakhan', 'Nehru Colony', 'Kaulagarh', 'Rajpur Road']],
  ['Morning Essentials Box', 'dairy', 'Milk, bread, eggs and the newspaper every day.',
    'Half a litre of milk, a loaf every other day, six eggs twice a week and your choice of newspaper.',
    1499, ALL, 'Delivered 6 – 7:30 am', 30, 'deliveries', 'Newspaper choice is fixed per month.', 'Tell us by 8 pm to skip a day.', 'doorstep', '1,3', ['Dalanwala', 'Patel Nagar']],

  ['SparkleHome Cleaning', 'home-cleaning', 'Weekly deep clean for a 2BHK.',
    'Four visits a month: sweeping, mopping, dusting, kitchen counters and two bathrooms. Supplies included.',
    2199, WEEK6, 'Slots 8 am – 6 pm', 4, 'visits', 'Up to 2BHK. Larger homes have their own plan.', 'Someone must be home for the first visit.', 'doorstep', '1,3', ['Rajpur Road', 'Vasant Vihar', 'Sahastradhara Road']],
  ['Daily Help Plan', 'home-cleaning', 'Daily sweeping, mopping and dishes.',
    'A verified helper visits every morning for sweeping, mopping and dishes. Replacement sent on leave days.',
    3499, WEEK6, '7 – 11 am', 26, 'visits', 'Four leave days a month are covered with a replacement.', 'Report issues through Subtize support.', 'doorstep', '1,3', ['Ballupur', 'Kaulagarh', 'Nehru Colony']],

  ['Smash Badminton Academy', 'sports', 'Coached badminton on wooden courts.',
    'Three coached sessions a week and open play on Sundays. Shuttles provided for coached sessions.',
    1399, 'tue,thu,sat,sun', '6 – 8 am and 5 – 8 pm', 16, 'sessions', 'Non-marking shoes only.', 'Open play is first come, first served.', 'in_person', '1,3,6', ['Race Course', 'Patel Nagar', 'Jakhan']],
  ['Kickstart Football Club', 'sports', 'Weekend football coaching for kids aged 6–15.',
    'Skill drills and small-sided games on turf, grouped by age. Monthly match day.',
    1199, 'sat,sun', '7 – 9 am', 8, 'sessions', 'Ages 6 to 15.', 'Shin guards required.', 'in_person', '1,3', ['Clement Town', 'Sahastradhara Road']],
  ['Shotokan Karate Dojo', 'sports', 'Karate for kids and adults, grading every quarter.',
    'Traditional Shotokan training three times a week. Belt grading every three months.',
    999, 'mon,wed,fri', '5 – 7 pm', 12, 'classes', 'Uniform bought separately.', 'Bow in and out of the dojo.', 'in_person', '1,3,6', ['Dalanwala', 'Prem Nagar']],

  ['Happy Paws Grooming', 'pet-care', 'Monthly bath, trim and nail clip for your dog.',
    'One full grooming session and one bath-only visit a month, at home or at the studio.',
    1299, 'tue,wed,thu,fri,sat', '10 am – 6 pm', 2, 'sessions', 'Dogs only. Large breeds may need two groomers.', 'Vaccination card required on the first visit.', 'doorstep', '1,3', ['Rajpur Road', 'Vasant Vihar', 'Jakhan']],
  ['Daily Dog Walker', 'pet-care', 'A 30-minute walk every morning.',
    'Background-checked walkers, one dog per walker, with a photo update after every walk.',
    2499, ALL, '6 – 8 am', 30, 'walks', 'One dog per plan.', 'Share any leash or behaviour notes before the first walk.', 'doorstep', '1,3', ['Dalanwala', 'Kaulagarh']],
];
